### ISSUE TITLE
etls doesn't compile under Windows

### ISSUE THREAD

**Issue by ghost** [florinpatrascu/bolt_sips#13]
Just for your information. :)
Even with all deps installed it doesn't work.
The owner has said that he doesn't have experience with Windows, so probably no fix is coming soon.

**Comment by florinpatrascu** [comment]
I appreciate the heads-up, thank you. Not having a Windows environment available for dev/testing, will be hard to find a solution from my end, but I will investigate a bit more and return with feedback. Thanks again!

**Comment by florinpatrascu** [comment]
Aaand... I noticed you managed to create the issue number 13, in both projects, here and in etls: https://github.com/kzemek/etls/issues/13 Coincidence?! :)

**Comment by ghost** [comment]
Yaiks!
I'll just use version 0.1.2 until someone figures it out :)

**Comment by florinpatrascu** [comment]
@onwarion - since my birthday is on the 13th of a month I won't name :) I thought I should deal with this lucky number somehow. So, please check the [with_ssl](https://github.com/florinpatrascu/bolt_sips/tree/with_ssl) branch and see how it works for you. Not the most elegant implementation (yet) but it is getting there :) 

Many thanks to @benwilson512 for feedback, on Slack!

**Comment by ghost** [comment]
The with_ssl branch compiled without errors.
I was able to connect and send a query.
This is enough to start my humble app development!
Thank you! 👍

**Comment by florinpatrascu** [comment]
w⦿‿⦿t!

**Comment by florinpatrascu** [comment]
@onwarion - this new version of Bolt.Sips, is now available at [Hex.pm](https://hex.pm/packages/bolt_sips/0.1.9), no need to use the `with_ssl` branch. Cheers!

**Comment by ghost** [comment]
Awesome! Thank you very much! :)
