### ISSUE TITLE
README improvements.

### ISSUE THREAD

**Issue by vic** [florinpatrascu/bolt_sips#4]
I'm thinking of doing the following improvements to the README.md

# Installation

- Just indicate the standard way of declaring a mix dependency.
 the example for the _github_ and _local_ dependency should be removed just to keep documentation concise. 

- Adapt the `Add the bolt_sips dependency the applications list` section.
 remove the `mod: {Bolt.Sips.Application, []}` part as `Bolt.Sips.Application` actually
 is an empty supervisor and does nothing.

 So I'm guessing the original intention of  `Bolt.Sips.Application` (correct me if I'm wrong)
 was to start Bolt.Sips with some configuration options (see snippet bellow). And in that case, remove the
 part that shows how to use `Bolt.Sips.start_link` manually.

 I'm currently doing something like this in my own app's supervision tree:

```elixir
children = [
       worker(Bolt.Sips, [Application.get_env(:bolt_sips, Bolt)])
]
```

# Usage

- Remove logger and mix_test_watch configurations.
- The snippet for adding `bolt_sips` to mix `:applications` should be only on Installation section.

# Testing

- dockerized neo4j
  Add example on how to start a local neo4j for testing (like the one travis uses from #2):
  `docker run -p 7687:7687 -e 'NEO4J_AUTH=none' neo4j:3.0.6`

**Comment by florinpatrascu** [comment]
Sure thing, thank you.

Re: Application - you're right, that was the intention. Bolt.Sips.start_link, was advertised mostly for testing or for more specific use cases. More than that, please take a look at this: [commit](https://github.com/CollabRx/callisto/commit/f72e281ff5aba55c6cf9e97f5d19ff91472d6991), for Callisto. After that commit, largely inspired by Ecto, using Neo4j.Sips (the HTTP based Neo4j driver) is much-much cleaner, from the client app's perspective. Example: https://github.com/florinpatrascu/callisto_demo The dilemma tho' was/is, if I start (again) recreating a Repo-like interface for Bolt.Sips, wouldn't be even better if I'll go for a full Ecto driver implementation on top of Bolt.Sips? The discussion here is more complex ... 

Now about the testing part. I totally agree with your related commit and README proposal. My initial plan tho' was to avoid docker and travis all together and use the [Bolt Server stub](https://github.com/neo4j-contrib/boltkit#stub-bolt-server) instead. But I suck at Python and that's why I don't have a better solution yet :) So Docker and Travis it is, and meanwhile I'll try to tame the Bolt Server stub :)

**Comment by vic** [comment]
Ok, will work on a branch for these README changes. 

Regarding the ecto-like repo, yeah, I also had something like that on my boltex fork from previous week, the main motivation was that users could have many connections to different neo4j servers (dunno if someone really needs something like that right now). But I'd go for keeping it simple and once someone needs to connect and have two "repos" simultaneously we could revisit it.

**Comment by florinpatrascu** [comment]
> Ok, will work on a branch for these README changes.

Awesome, thank you!

re: connections to different servers. Yeah, let's keep it simple, also b/c I couldn't find a realistic scenario where segregating the server roles with a simple HAProxy would not work; a solution which obviously doesn't need any support from bolt_sips, as it stands. Also, the Neo4j clustering support is young and personally I still need to learn more about it before I can have a more productive opinion about the connections to Neo4j servers, in general.
