### ISSUE TITLE
Road to neo4j 4 and streaming

### ISSUE THREAD

**Issue by kristofka** [florinpatrascu/bolt_sips#81]
Hi Florin,

Neo4j v4 is near, I've run the tests against the latest version and they fail because the syntax for 
parameters names `{param...}` is deprecated. I think we should make a new branch with updated
tests, just to see where we're standing.
Would it be ok if I started a new branch for this purpose?

Also, I know you're planning streaming support, and I would like to know what the strategy should be in that regard. I'd be glad to help on that front.

regards.

**Comment by florinpatrascu** [comment]
Absolutely, please feel free to create the new branch, thank you! In relation to streaming, I am not able to find a clean design, yet. The causal cluster makes this even more complicated. Will try to create a branch and prototype in the open. I’ll take another shot at this :)

**Comment by Simrayz** [comment]
Hi Florin!
Thank you for creating this library, I rely heavily on it in my startup. What is the status of 4.0 support? We don't need the functionality in it at this moment, but I'm interested in what your roadmap is :)

**Comment by kristofka** [comment]
Hi,

I can’t speak for Florin, but I wanted to work on that and then I got side tracked. It’s still something that’s on my mind and I believe/hope that I’ll be able to take a stab at it by the end of September. 
-- 
Kristof 




26 Jul 2020, 15:42 by notifications@github.com:

**Comment by florinpatrascu** [comment]
Hi @Simrayz - thank you for using our driver, and for your kind words. Was trying to get myself into the "zone" again, after the last non-trivial release we published, but had to postpone it due to other priorities; am also being very busy at my day job and currently lacking the time this new upgrade would demand. Hopefully this pandemic goes away soon and we can all find the free time and/or the resources we need for continuing doing open source. Meanwhile, even tho I can't comment in behalf of @dominique-vassard and @kristofka, I will support this version and accept any PRs from the community. We are all independent developers, contributing to this driver being driven by our passion for learning, but as far as I am concerned, my free time is very limited these days. I too hope to find more time coming Sep/Oct, this year. HTH - ッFlorin

**Comment by dominique-vassard** [comment]
Hi,
Glad to hear you're using the driver.
Everything has been said regarding future development for No4j 4 support.
On my part, I have enough (too much) work with [seraph](https://github.com/dominique-vassard/seraph) and my new job for now.

But you can still enjoy Neo4j 4 with bolt_sips. Apart for the streaming features, everything else is made available through Cypher (even the new subquery feature of 4.1), then you can safely use current driver version and use the last Neo4j version.

Dominique
